name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: make setup

      - name: Lint code
        run: make lint

      - name: Validate code
        run: make validate
