name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check modified paths
        id: paths
        uses: dorny/paths-filter@v3
        with:
          list-files: "json"
          filters: |
            illegal:
              - '!chains/**'

      - name: Fail if PR modifies files outside chains
        if: steps.paths.outputs.illegal == 'true'
        run: |
          echo "PR contains changes outside the chains directory."
          echo "Illegal files:"
          echo "${{ steps.paths.outputs.illegal_files }}"
          exit 1

      - name: Setup environment
        run: make setup

      - name: Run Prettier
        run: make format 

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "style: autoformat with Prettier"
            git push
            echo "Formatting changes pushed, failing job to re-trigger workflow."
            exit 1
          else
            echo "No formatting changes, proceeding to validation."
          fi

      - name: Validate code
        run: make validate
